name = "ExtXYZ"
uuid = "352459e4-ddd7-4360-8937-99dcb397b478"
authors = ["James Kermode <J.R.Kermode@warwick.ac.uk> and contributors"]
version = "0.1.6-DEV"

[deps]
extxyz_jll = "6ecdc6fc-93a8-5528-aee3-ac7ae1c60be7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
