name = "ExtXYZ"
uuid = "352459e4-ddd7-4360-8937-99dcb397b478"
authors = ["James Kermode <J.R.Kermode@warwick.ac.uk> and contributors"]
version = "0.1.0"

[deps]
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
extxyz_jll = "6ecdc6fc-93a8-5528-aee3-ac7ae1c60be7"

[compat]
JuLIP = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
